### PR TITLE
415 unsupported media type

### PR DESCRIPTION
**Pull request by Supernoodles99**
i made a thing

### CODE REVIEW

**Review by showierdata9978 — CHANGES_REQUESTED** [review]
please make 50x50 or close to it, and it is required to be a jpg.

**Comment by showierdata9978** [comment]
please remove the extra file

**Comment by Supernoodles99** [comment]
[done](https://github.com/Supernoodles99/http-meower/blob/main/imgs/415.jpg)

**Review by showierdata9978 — APPROVED** [review]

**Pull request merged**
