### PR TITLE
Update some

### PR DESCRIPTION
**Pull request by mybearworld**
**Updated:**
- 300 (Multiple Choices)
- 307 (Temporary Redirect)
- 308 (Permanent Redirect)
- 400 (Bad Request)
- 404 (Not Found)
- 418 (I'm A Teapot)

### CODE REVIEW

**Comment by showierdata9978** [comment]
why'd you remove ```407: "Proxy Authentication Required",
  408: "Request Timeout"```,?

**Comment by mybearworld** [comment]
> why'd you remove `407: "Proxy Authentication Required", 408: "Request Timeout"`,?

Because they're supposed to be 307 (Temporary Redirect) and 308 (Permanent Redirect)

**Comment by mybearworld** [comment]
> Both are valid HTTP codes.

The icons with the names `407.jpg` and `408.jpg` are the symbols shown as 307 and 308 on http.meower.org.

**Comment by mybearworld** [comment]
Now this branch doesn't delete any images, yay :Þ

**Comment by mybearworld** [comment]
These seem to all have been reverted...

**Comment by Kabezz** [comment]
if I can i could bring them back (I hope (maybe (possibly (I hope (maybe (possibly (I hope)))))))

**Pull request merged**
